export const ADD_MOVIES = "ADD_MOVIES";
export const ADD_MOVIE_TO_LIST = "ADD_MOVIE_TO_LIST";
export const REMOVE_MOVIE_TO_LIST = "REMOVE_MOVIE_TO_LIST";
export const SET_LINKACTIVE = "SET_LINKACTIVE";
export const ADD_POST_MOVIES = "ADD_POST_MOVIES";
